;; Each new term in the Fibonacci sequence is generated by adding the
;; previous two terms. By starting with 1 and 2, the first 10 terms will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do
;; not exceed four million, find the sum of the even-valued terms.
;;
;; A: 4613732


(define problem-2
  (lambda (limit)
    (call/cc
     (lambda (brk)
       (letrec ((fib-sum
                 (lambda (init sum esum)
                   (let ((new-sum (+ init sum)))
                     (if (> new-sum limit)
                         (brk esum)
                         (if (even? new-sum)
                             (fib-sum sum new-sum (+ esum new-sum))
                             (fib-sum sum new-sum esum)))))))
         (fib-sum 1 1 0))))))

(display (problem-2 4000000))
(display "\n")
